### ISSUE TITLE
Expose Financial Batch field on Submit Credit Card

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.easybatch#4]
Currently, no Financial Batch field is exposed on Submit Credit Card contribution form. However, there is a validation error when it is not filled in.

Solution: Expose this field.

**Comment by monishdeb** [comment]
Submitted PR https://github.com/JMAConsulting/biz.jmaconsulting.easybatch/pull/6

**Comment by JoeMurray** [comment]
@Edzelopez could you QA and merge and resolve as appropriate? Thx.

**Comment by monishdeb** [comment]
@Edzelopez @JoeMurray I am closing this issue as resolved as AO-94 ticket is addressed and closed and #6 is merged. Thanks!
