### ISSUE TITLE
per processor auto-batches should be for payment trxns only

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.easybatch#5]
On Payment Processor Edit form, the auto-batching should be set for **payment** transactions, not for **non-payment** transactions
![2018-09-19_12-25-21](https://user-images.githubusercontent.com/300943/45767024-1c46e000-bc07-11e8-801a-8fdd181b1b72.png)

To do:
- change ' Create Automatic Daily Financial Batches?' to ' Create Automatic Daily Financial Batches for Payments?'
- when the payment processor selected for a backend credit card contribution is setup for autobatching payment transactions, hide the Batch field and set it to the processor's current open autobatch for payments; when the payment processor is not autobatching payments, reveal the batch field

Test the following
- [ ] online dummy processor payments

- [ ] backend dummy processor payments (pending fix)

**Comment by Edzelopez** [comment]
Made the changes above, will test for items

**Comment by JoeMurray** [comment]
Looks good on jma.st

**Comment by Edzelopez** [comment]
This has made it's way to master.
